spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-book
    username: postgres
    password: 1912
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog-master.xml